-- ============================================================
-- 030_catalogo_2026-10-07.sql
-- Gerado por catalogo/catalogar.py em 07/10/2026 19:41 (rodado no Supabase
-- às 19:54). Este arquivo foi recriado a partir do banco, pro histórico
-- do repositório bater com o que foi rodado: 84 veículos (83 validados +
-- o Estadão, incluído à mão).
-- on conflict (url) do nothing: rodar duas vezes não duplica nada.
-- ============================================================

insert into feed_catalog (category, name, url, description, kind) values
    ('Ciência', 'Agência FAPESP', 'https://agencia.fapesp.br/rss', 'Reportagens e notícias em ciência e tecnologia', 'rss'),
    ('Ciência', 'Galileu', 'https://revistagalileu.globo.com/rss/galileu', 'Galileu', 'rss'),
    ('Ciência', 'Inovação Tecnológica', 'https://www.inovacaotecnologica.com.br/boletim/rss.xml', 'Notícias de ciência, tecnologia e inovação.', 'rss'),
    ('Ciência', 'National Geographic Brasil', 'https://news.google.com/rss/search?q=site%3Anationalgeographicbrasil.com&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Entretenimento', 'Pipoca Moderna', 'https://pipocamoderna.com.br/feed/', 'Entretenimento e Cultura Pop', 'rss'),
    ('Entretenimento', 'Plano Crítico', 'https://www.planocritico.com/feed/', 'Crítica e Entretenimento', 'rss'),
    ('Entretenimento', 'Purepeople', 'https://news.google.com/rss/search?q=site%3Apurepeople.com.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Entretenimento', 'Quem', 'https://revistaquem.globo.com/rss/quem', 'Fique por dentro das últimas notícias sobre os famosos! Confira entrevistas exclusivas, destaques sobre TV, novelas,…', 'rss'),
    ('Entretenimento', 'Rolling Stone Brasil', 'https://rollingstone.com.br/feed/', null, 'rss'),
    ('Entretenimento', 'Tenho Mais Discos Que Amigos!', 'https://www.tenhomaisdiscosqueamigos.com/feed/', 'Fundado em 2009, o TMDQA! é um dos principais portais de conteúdo sobre Música, Cultura e Entretenimento do Brasil.', 'rss'),
    ('Esportes', 'Goal Brasil', 'https://news.google.com/rss/search?q=site%3Agoal.com/br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Esportes', 'Meu Timão', 'https://www.meutimao.com.br/feed/', 'Acompanhe todas as notícas do Corinthians em um só lugar', 'rss'),
    ('Esportes', 'Olimpíada Todo Dia', 'https://www.olimpiadatododia.com.br/feed/', 'Portal do Esporte Olímpico e Paralímpico do Brasil', 'rss'),
    ('Esportes', 'Torcedores', 'https://www.torcedores.com/feed', 'Reportagens, colunas, lives, fotos e vídeos diários sobre os principais acontecimentos do futebol, da mídia esportiva,…', 'rss'),
    ('Finanças', 'Bloomberg Línea', 'https://www.bloomberglinea.com.br/arc/outboundfeeds/rss.xml', 'Bloomberg Línea Brasil News Feed', 'rss'),
    ('Finanças', 'Brazil Journal', 'https://braziljournal.com/feed/', 'Quem faz o PIB lê.', 'rss'),
    ('Finanças', 'Época Negócios', 'https://epocanegocios.globo.com/rss/epocanegocios', 'Home | Época Negócios', 'rss'),
    ('Finanças', 'Forbes Brasil', 'https://forbes.com.br/feed/', 'Forbes, a mais conceituada revista de negócios e economia do mundo.', 'rss'),
    ('Finanças', 'InvestNews', 'https://investnews.com.br/feed/', 'Sua dose diária de inteligência financeira', 'rss'),
    ('Finanças', 'NeoFeed', 'https://neofeed.com.br/feed/', 'Negócios, Empreendedorismo, Inovação e Transformação digital | NeoFeed', 'rss'),
    ('Finanças', 'Valor Econômico', 'https://valor.globo.com/rss/valor', 'O Valor Econômico é o mais importante veículo de economia, finanças e negócios do Brasil. Traz notícias, cotações,…', 'rss'),
    ('Finanças', 'Valor Investe', 'https://valorinveste.globo.com/sitemap/valorinveste/news.xml', null, 'sitemap'),
    ('Humor', 'Ah Negão!', 'https://www.ahnegao.com.br/feed', 'Memes | Videos | GIFs | Imagens Engraçadas - Site de humor atualizado diariamente desde 2008.', 'rss'),
    ('Mundo', 'DW Brasil', 'https://news.google.com/rss/search?q=site%3Adw.com/pt-br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Mundo', 'ONU News', 'https://news.google.com/rss/search?q=site%3Anews.un.org/pt&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Mundo', 'swissinfo.ch', 'https://www.swissinfo.ch/por/sitemap-news.xml#caminho=/por', null, 'sitemap'),
    ('Notícias', 'A Crítica', 'https://news.google.com/rss/search?q=site%3Aacritica.com&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Notícias', 'A Tarde', 'https://atarde.com.br/rss', 'Portal A TARDE', 'rss'),
    ('Notícias', 'A Tribuna', 'https://news.google.com/rss/search?q=site%3Aatribuna.com.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Notícias', 'Agência Brasil', 'https://news.google.com/rss/search?q=site%3Aagenciabrasil.ebc.com.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Notícias', 'Agência Pública', 'https://apublica.org/feed/', 'A primeira e mais premiada agência de jornalismo investigativo do Brasil.', 'rss'),
    ('Notícias', 'Band', 'https://news.google.com/rss/search?q=site%3Aband.uol.com.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Notícias', 'Bem Paraná', 'https://www.bemparana.com.br/feed/', 'Notícias do Paraná, Brasil e muito mais!', 'rss'),
    ('Notícias', 'Brasil de Fato', 'https://www.brasildefato.com.br/feed/', 'Uma visão popular do Brasil e do mundo.', 'rss'),
    ('Notícias', 'Campo Grande News', 'https://www.campograndenews.com.br/rss/rss.xml', 'Veja notícias em Campo Grande e Mato Grosso do Sul - Campo Grande News - Últimas Notícias de economia, política,…', 'rss'),
    ('Notícias', 'CNN Brasil', 'https://admin.cnnbrasil.com.br/feed/', 'Notícias Ao Vivo do Brasil e do Mundo', 'rss'),
    ('Notícias', 'Correio', 'https://www.correio24horas.com.br/0000/01/news-sitemap.xml', null, 'sitemap'),
    ('Notícias', 'Correio Braziliense', 'https://www.correiobraziliense.com.br/sitemap/map/day/sitemap-news.xml', null, 'sitemap'),
    ('Notícias', 'Correio do Povo', 'https://www.correiodopovo.com.br/sitemap_news.xml', null, 'sitemap'),
    ('Notícias', 'Diário de Pernambuco', 'https://www.diariodepernambuco.com.br/sitemap-news.xml', null, 'sitemap'),
    ('Notícias', 'Diário do Comércio', 'https://diariodocomercio.com.br/feed/', 'Impressão digital da economia mineira', 'rss'),
    ('Notícias', 'Diário do Nordeste', 'https://diariodonordeste.verdesmares.com.br/cmlink/feed-1.3009099', 'feed', 'rss'),
    ('Notícias', 'Estadão', 'https://www.estadao.com.br/arc/outboundfeeds/feeds/rss/sections/geral/?body=%7B%22layout%22:%22google-news%22%7D', 'As últimas notícias do Estadão', 'rss'),
    ('Notícias', 'Estadão Economia', 'https://www.estadao.com.br/arc/outboundfeeds/feeds/rss/sections/economia/?body=%7B%22layout%22:%22google-news%22%7D', 'As principais e as últimas notícias do Brasil e do mundo com credibilidade na informação sobre política, economia,…', 'rss'),
    ('Notícias', 'Estadão Política', 'https://www.estadao.com.br/arc/outboundfeeds/feeds/rss/sections/politica/?body=%7B%22layout%22:%22google-news%22%7D', 'As principais e as últimas notícias do Brasil e do mundo com credibilidade na informação sobre política, economia,…', 'rss'),
    ('Notícias', 'Estado de Minas', 'https://www.em.com.br/feed', 'Estado de Minas Information Syndication RSS Feed', 'rss'),
    ('Notícias', 'Extra', 'https://extra.globo.com/rss/extra', 'Leia as principais notícias do Rio e do mundo', 'rss'),
    ('Notícias', 'Folha de S.Paulo', 'https://www.folha.uol.com.br/news-sitemap.xml', null, 'sitemap'),
    ('Notícias', 'g1', 'https://g1.globo.com/rss/g1/', 'Últimas notícias do Brasil e do mundo, sobre política, economia, emprego, educação, saúde, meio ambiente, tecnologia,…', 'rss'),
    ('Notícias', 'Gazeta Digital', 'https://news.google.com/rss/search?q=site%3Agazetadigital.com.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Notícias', 'Gazeta do Povo', 'https://news.google.com/rss/search?q=site%3Agazetadopovo.com.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Notícias', 'GZH', 'https://news.google.com/rss/search?q=site%3Agauchazh.clicrbs.com.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Notícias', 'Intercept Brasil', 'https://news.google.com/rss/search?q=site%3Aintercept.com.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Notícias', 'IstoÉ', 'https://istoe.com.br/feed', 'O mais combativo portal de informação e interesse geral do Brasil e do mundo', 'rss'),
    ('Notícias', 'Jornal do Brasil', 'https://www.jb.com.br/sitemap-news.xml', null, 'sitemap'),
    ('Notícias', 'Jornal do Comércio', 'https://www.jornaldocomercio.com/sitemap-news.xml', null, 'sitemap'),
    ('Notícias', 'Jornal do Commercio', 'https://jc.uol.com.br/ultimas/rss.xml', 'Acompanhe as últimas notícias em tempo real de Pernambuco, do Brasil e do mundo. Atualizações minuto a minuto sobre…', 'rss'),
    ('Notícias', 'Jovem Pan', 'https://jovempan.com.br/feed/', null, 'rss'),
    ('Notícias', 'Metrópoles', 'https://www.metropoles.com/feed', 'O seu portal de notícias', 'rss'),
    ('Notícias', 'Nexo', 'https://www.nexojornal.com.br/rss.xml', 'Informação clara e bem explicada você encontra aqui. Nexo, leitura obrigatória para quem quer entender o contexto das…', 'rss'),
    ('Notícias', 'NSC Total', 'https://www.nsctotal.com.br/feed', 'Notícias de Santa Catarina, Brasil e do Mundo', 'rss'),
    ('Notícias', 'O Dia', 'https://odia.ig.com.br/_conteudo/ultimas-noticias/rss.xml', 'Acompanhe nosso plantão de notícias', 'rss'),
    ('Notícias', 'O Globo', 'https://oglobo.globo.com/rss/oglobo', 'Fique atualizado com as principais notícias e acompanhe tudo o que está acontecendo no Brasil e no mundo. Acesse O…', 'rss'),
    ('Notícias', 'O Liberal', 'https://www.oliberal.com/cmlink/futebol-oliberal-com-1.969299', 'Últimas notícias sobre o futebol regional, nacional e mundial.', 'rss'),
    ('Notícias', 'O Popular', 'https://news.google.com/rss/search?q=site%3Aopopular.com.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Notícias', 'O Povo', 'https://www.opovo.com.br/sitemap-news-day.xml', null, 'sitemap'),
    ('Notícias', 'O Tempo', 'https://www.otempo.com.br/news-sitemap.xml', null, 'sitemap'),
    ('Notícias', 'piauí', 'https://piaui.uol.com.br/feed/', 'A piauí é uma revista mensal criada em 2006 com o objetivo de contar histórias – apuradas com tempo largo, escritas…', 'rss'),
    ('Notícias', 'R7', 'https://noticias.r7.com/arc/outboundfeeds/sitemap-news-index/', null, 'sitemap'),
    ('Notícias', 'SBT News', 'https://sbtnews.sbt.com.br/rss.xml', 'O fato como ele é. Notícias 24h, Ao Vivo, do Brasil e do Mundo sobre política, economia, internacional, saúde,…', 'rss'),
    ('Notícias', 'Terra', 'https://www.terra.com.br/rss', 'Brasil Feed', 'rss'),
    ('Notícias', 'Times Brasil CNBC', 'https://timesbrasil.com.br/feed/', null, 'rss'),
    ('Notícias', 'UOL Notícias', 'https://news.google.com/rss/search?q=site%3Anoticias.uol.com.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Notícias', 'Veja', 'https://veja.abril.com.br/ultimas-noticias/feed/', 'Principais informações sobre política, eleições, economia, internacional, saúde, tecnologia, esporte e cultura', 'rss'),
    ('Política', 'Agência Câmara', 'https://news.google.com/rss/search?q=site%3Acamara.leg.br/noticias&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Política', 'Agência Senado', 'https://www12.senado.leg.br/noticias/RSS', null, 'rss'),
    ('Política', 'JOTA', 'https://portal.jota.info/feed/jotaunico', 'Por instituições mais previsíveis', 'rss'),
    ('Saúde', 'Fiocruz', 'https://news.google.com/rss/search?q=site%3Aportal.fiocruz.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Saúde', 'Minha Vida', 'https://news.google.com/rss/search?q=site%3Aminhavida.com.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Tecnologia', 'Baguete', 'https://news.google.com/rss/search?q=site%3Abaguete.com.br&hl=pt-BR&gl=BR&ceid=BR:pt-419', 'Via Google Notícias', 'rss'),
    ('Tecnologia', 'Mobile Time', 'https://www.mobiletime.com.br/feed/', 'Notícias sobre o mercado de tecnologia móvel', 'rss'),
    ('Tecnologia', 'Mundo Conectado', 'https://www.mundoconectado.com.br/feed/', 'Fonte de informação sobre Tecnologia e Entretenimento', 'rss'),
    ('Tecnologia', 'Oficina da Net', 'https://www.oficinadanet.com.br/rss/geral', 'Desde 2005 no ar, o Oficina da Net tem o compromisso em informar as novidades do mundo de tecnologia, além de artigos,…', 'rss'),
    ('Tecnologia', 'Startups', 'https://startups.com.br/feed/', 'O epicentro da tecnologia e da inovação', 'rss')
on conflict (url) do nothing;
